Web UI/allauth/account/urls.py
from django.urls import path, re_path

from . import views


urlpatterns = [
    path("signup/", views.signup, name="account_signup"),
    path("login/", views.login, name="account_login"),
    path("logout/", views.logout, name="account_logout"),
    path("password/change/", views.password_change,
         name="account_change_password"),
    path("password/set/", views.password_set, name="account_set_password"),
    path("inactive/", views.account_inactive, name="account_inactive"),

    # E-mail
    path("email/", views.email, name="account_email"),
    path("confirm-email/", views.email_verification_sent,
         name="account_email_verification_sent"),
    re_path(r"^confirm-email/(?P<key>[-:\w]+)/$", views.confirm_email,
            name="account_confirm_email"),

    # password reset
    path("password/reset/", views.password_reset,
         name="account_reset_password"),
    path("password/reset/done/", views.password_reset_done,
         name="account_reset_password_done"),
    re_path(r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
            views.password_reset_from_key,
            name="account_reset_password_from_key"),
    path("password/reset/key/done/", views.password_reset_from_key_done,
         name="account_reset_password_from_key_done"),
]

Web UI/allauth/socialaccount/providers/agave/urls.py
from allauth.socialaccount.providers.agave.provider import AgaveProvider
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns


urlpatterns = default_urlpatterns(AgaveProvider)

Web UI/allauth/socialaccount/providers/asana/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import AsanaProvider


urlpatterns = default_urlpatterns(AsanaProvider)

Web UI/allauth/socialaccount/providers/auth0/urls.py
# -*- coding: utf-8 -*-
from allauth.socialaccount.providers.auth0.provider import Auth0Provider
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns


urlpatterns = default_urlpatterns(Auth0Provider)

Web UI/allauth/socialaccount/providers/azure/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import AzureProvider


urlpatterns = default_urlpatterns(AzureProvider)

Web UI/allauth/socialaccount/providers/baidu/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import BaiduProvider


urlpatterns = default_urlpatterns(BaiduProvider)

Web UI/allauth/socialaccount/providers/bitly/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import BitlyProvider


urlpatterns = default_urlpatterns(BitlyProvider)

Web UI/allauth/socialaccount/providers/box/urls.py
from allauth.socialaccount.providers.oauth.urls import default_urlpatterns

from .provider import BoxOAuth2Provider


urlpatterns = default_urlpatterns(BoxOAuth2Provider)

Web UI/allauth/socialaccount/providers/cern/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import CernProvider


urlpatterns = default_urlpatterns(CernProvider)

Web UI/allauth/socialaccount/providers/daum/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import DaumProvider


urlpatterns = default_urlpatterns(DaumProvider)

Web UI/allauth/socialaccount/providers/edx/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import EdxProvider


urlpatterns = default_urlpatterns(EdxProvider)

Web UI/allauth/socialaccount/providers/fxa/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import FirefoxAccountsProvider


urlpatterns = default_urlpatterns(FirefoxAccountsProvider)

Web UI/allauth/socialaccount/providers/line/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import LineProvider


urlpatterns = default_urlpatterns(LineProvider)

Web UI/allauth/socialaccount/providers/vk/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import VKProvider


urlpatterns = default_urlpatterns(VKProvider)

Web UI/allauth/socialaccount/providers/xing/urls.py
from allauth.socialaccount.providers.oauth.urls import default_urlpatterns

from .provider import XingProvider


urlpatterns = default_urlpatterns(XingProvider)

Web UI/allauth/socialaccount/providers/ynab/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import YNABProvider


urlpatterns = default_urlpatterns(YNABProvider)

Web UI/allauth/socialaccount/providers/zoho/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import ZohoProvider


urlpatterns = default_urlpatterns(ZohoProvider)

Web UI/allauth/socialaccount/providers/zoom/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import ZoomProvider


urlpatterns = default_urlpatterns(ZoomProvider)

Web UI/allauth/socialaccount/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('login/cancelled/', views.login_cancelled,
         name='socialaccount_login_cancelled'),
    path('login/error/', views.login_error,
         name='socialaccount_login_error'),
    path('signup/', views.signup, name='socialaccount_signup'),
    path('connections/', views.connections, name='socialaccount_connections')
]

Web UI/allauth/urls.py
from importlib import import_module

from django.urls import include, path

from allauth.socialaccount import providers

from . import app_settings


urlpatterns = [path('', include('allauth.account.urls'))]

if app_settings.SOCIALACCOUNT_ENABLED:
    urlpatterns += [path('social/', include('allauth.socialaccount.urls'))]

# Provider urlpatterns, as separate attribute (for reusability).
provider_urlpatterns = []
for provider in providers.registry.get_list():
    try:
        prov_mod = import_module(provider.get_package() + '.urls')
    except ImportError:
        continue
    prov_urlpatterns = getattr(prov_mod, 'urlpatterns', None)
    if prov_urlpatterns:
        provider_urlpatterns += prov_urlpatterns
urlpatterns += provider_urlpatterns

Web UI/apps/core/urls.py
from django.urls import path

from . import views
app_name = "core"
urlpatterns = [
    path('', views.index, name="index"),
    path('newsletter', views.newsletter, name='newsletter'),
    path("accounts/profile/", views.profileview, name="profile"),
    path('team/', views.team, name="team"),
    path('contact/', views.contact, name="contact"),
    path('portal/', views.portal, name="portal"),
]

Web UI/team_planet/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls', namespace='core')),
    path('accounts/', include('allauth.urls')),
]

Web UI/templates/addons/footer.html
{% load static %}
{% if request.path != '/' %}
<div class="footer pt-11 pb-3 bg-dark text-base">
    {% else %}
    <div class="footer pt-11 pb-3 text-base"
        style="background: url({% static 'img/earth.jpg' %}); background-size: cover; background-repeat: no-repeat; background-position: center; background-attachment: fixed">
        {% endif %}
        <div class="container">
            <div class="row">

                <div class="col-lg-6 col-md-6 col-12" style="background:rgba(0, 0, 0, 0.85)">
                    <div class="mb-4">
                        <h4 class="mb-4 text-white">Subscribe to our newsletter</h4>
                        <div>
                            <p class="text-light">Subscribe to get notified about our project.</p>
                            <form action="{% url 'core:newsletter' %}" method="POST">
                                {% csrf_token %}
                                <div class="mb-3">
                                    <input type="email" name='email' class="form-control border-white"
                                        placeholder="Email Address" required="">
                                </div>
                                <button type="submit" class="btn btn-primary">Subscribe</button>
                            </form>

                        </div>
                    </div>
                </div>
                <ul style="text-align:center;" class="list-inline align-center text-white">
                    <li class="list-inline-item"><b>© 2020 Team Planet.</b></li>
                </ul>
            </div>
        </div>
    </div>

Web UI/templates/addons/navbar.html
 <!-- Navigation -->
 <nav class="navbar navbar-expand-lg navbar-light shadow-lg">
     <div class="container-fluid">
         <a class="navbar-brand" href="{% url 'core:index' %}">Team Planet</a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
             aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarNavDropdown">
             <ul class="navbar-nav">
                 <li class="nav-item">
                     <a class="nav-link {% if request.path == '/' %}active{% endif %}" aria-current="page"
                         href="{% url 'core:index' %}">Home</a>
                 </li>
                 <li class="nav-item">
                     <a class="nav-link  {% if request.path == '/team/' %}active{% endif %}"
                         href="{% url 'core:team' %}">Our Team</a>
                 </li>
                 <li class="nav-item">
                     <a class="nav-link  {% if request.path == '/contact/' %}active{% endif %}"
                         href="{% url 'core:contact' %}">Contact</a>
                 </li>
                 {% comment %}
                 <!-- <li class="nav-item">
                            <a class="nav-link" href="">Portal</a>
                        </li> --> {% endcomment %}
             </ul>
             <ul class="navbar-nav ml-auto">


                 {% if user.is_authenticated %}
                 <li class="nav-item">
                     <a class="btn btn-primary-soft mt-1 mx-1 btn-lg" aria-current="page"
                         href="{% url 'core:portal' %}">Go To Portal</a>
                 </li>
                 <li class="nav-item">
                     <a class="btn btn-danger-soft mt-1 mx-1 btn-lg" aria-current="page"
                         href="{% url 'account_logout' %}">Logout</a>
                 </li>
                 {% else %}
                 <li class="nav-item">
                     <a class="btn btn-info-soft mt-1 btn-lg" aria-current="page" href="{% url 'account_signup' %}">Sign
                         Up</a>
                 </li>
                 <li class="nav-item">
                     <a class="btn btn-success-soft mt-1 mx-1    btn-lg" aria-current="page"
                         href="{% url 'account_login' %}">Login</a>
                 </li>
                 {% endif %}


             </ul>
         </div>
     </div>
 </nav>
 <!-- End Navigation -->

Web UI/templates/base.html
<!DOCTYPE html>
{% load static %}
<!-- Team Planet NASA Spaceapps challenge 2020 -->
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Team Planet | {% block title %}{% endblock title %} {% block head_title %}
        {% endblock head_title %} </title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'css/theme.css' %}">
</head>

<body>
    {% include 'addons/navbar.html' %}
    <div class="main mb-20">

        {% block content %}
        {% endblock content %}

    </div>
    {% include 'addons/footer.html' %}
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/all.min.js' %}"></script>
    <script src="{% static 'js/fontawesome.min.js' %}"></script>
    <script src="{% static 'js/theme.js' %}"></script>
</body>

</html>

Web UI/templates/portal/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Portal
{% endblock title %}
{% block content %}

<div class="mt-6">

    <div class="pt-lg-13 pb-lg-14 py-8 bg-dark">
        <div class="container">
            <div class="row">
                <div class="offset-lg-2 col-lg-8 col-md-12 col-12">
                    <div class="text-center mb-12">
                        <h2 class="text-white mb-3 h1">
                            Welcome, {{user.profile.fname}}.
                        </h2>
                        <p class="lead mb-5">
                            These in depth analysis of the geographical information from the satellite imagery can help
                            us analyze the different indepth factors and mitigate any critical situations which would
                            greatly aid in our efforts to take immediate actions to sustain our planet. This analysis
                            has
                            been done for a particular location considering the time-constraints of the event however we
                            can analyze with available satellite datasets for any location and wide variety of
                            sustainable constriants. Our plan is to analyze, predict and suggest possible responses.
                            And due to the limited time, we couldn't directly include our findings here. But it can be
                            checked out on Google colab or GitHub repo.
                        </p>
                        <a href="https://colab.research.google.com/github/shekhar-git-hub/Project-Space-Watch/blob/main/analyzing_visualizing_large_scale_satellite_imagery.ipynb"
                            class="btn btn-info btn-lg mr-1">Google Colab</a>
                        <a href="https://colab.research.google.com/github/shekhar-git-hub/Project-Space-Watch/blob/main/analyzing_visualizing_large_scale_satellite_imagery.ipynb"
                            class="btn btn-info btn-lg">GitHub Repo</a>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container mt-lg-n14 mt-n10 pb-lg-6">
        <div class="row">
            <div class="col-lg-4 col-md-6 col-12">
                <div class="mb-4 mb-lg-0">
                    <a href="https://github.com/awebisam/team_planet_nasa2020"><img src="{% static 'img/src.png' %}"
                            alt="" class="img-fluid w-100 border-top border-primary border-top-4 rounded-top"></a>
                    <div class="border-top-0 border rounded-bottom bg-white">
                        <div class="p-4">
                            <h4>Source code</h4>
                            <p>
                                This site has been built with HTML, CSS, JS, Django and SQLite3.
                            </p>
                            <a href="https://github.com/awebisam/team_planet_nasa2020" class="btn-primary-link">GitHub
                                Repo</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-12">
                <div class="mb-4 mb-lg-0">
                    <a href="{% url 'core:team' %}"><img src="{% static 'img/team.png' %}" alt=""
                            class="img-fluid w-100 border-top border-primary border-top-4 rounded-top"></a>
                    <div class="border-top-0 border rounded-bottom bg-white">
                        <div class="p-4">
                            <h4>Our Team</h4>
                            <p>
                                We are an awesome and hardworking team of 5 people from various expertise.
                            </p>
                            <a href="{% url 'core:team' %}" class="btn-primary-link">Our Team</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-12 d-md-none d-lg-block">
                <div class="mb-4 mb-lg-0">
                    <a href="{% url 'core:contact' %}"><img src="{% static 'img/feedback.png' %}" alt=""
                            class="img-fluid w-100 border-top border-primary border-top-4 rounded-top"></a>
                    <div class="border-top-0 border rounded-bottom bg-white">
                        <div class="p-4">
                            <h4>Have Your Say</h4>
                            <p>
                                We believe that perfection is a myth. We need your suggestions.
                            </p>
                            <a href="{% url 'core:contact' %}" class="btn-primary-link">Contact Us</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

</div>

{% endblock %}